---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable
before_cache:
  - cd $TRAVIS_BUILD_DIR
  - rm -rf $TRAVIS_BUILD_DIR/node_modules/.bin $TRAVIS_BUILD_DIR/node_modules/@onedoes

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/packages/pwa/app/bower_components

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc

before_script:
  - '
    if [ "$TRAVIS_BRANCH" != "master" ]; then
      export SAUCE_ACCESS_KEY=$PR_SAUCE_ACCESS_KEY;
      export SAUCE_USERNAME=$PR_SAUCE_USERNAME;
    fi;
    '
stages:
  - Local tests

  - name: Remote tests
    if: NOT type = pull_request

  - name: Deploy
    if: tag =~ ^v0

jobs:
  include:
    - stage: Local tests
      script:
        - cd packages/pwa
        - xvfb-run yarn run wct
    - stage: Remote tests
      env: BROWSER=chrome
      script:
        - cd packages/pwa;
        - yarn run wct --plugin sauce
    -
      env: BROWSER=firefox
      script:
        - cd packages/pwa;
        - yarn run wct --plugin sauce
    -
      env: BROWSER=edge
      script:
        - cd packages/pwa;
        - yarn run wct --plugin sauce
    -
      env: BROWSER=android
      script:
        - cd packages/pwa;
        - yarn run wct --plugin sauce
    -
      env: BROWSER=iphone
      script:
        - cd packages/pwa;
        - yarn run wct --plugin sauce

    - stage: Deploy
      script:
        - yarn run build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: $TRAVIS_BUILD_DIR/packages/pwa/dist
        github-token: $GITHUB_TOKEN
