---
git:
  depth: 5
sudo: false

cache:
  yarn: true
  directories:
    - app/bower_components
    - node_modules

language: node_js
node_js: node

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then
      export SAUCE_ACCESS_KEY=$PR_SAUCE_ACCESS_KEY;
      export SAUCE_USERNAME=$PR_SAUCE_USERNAME;
    fi

before_script:
  - npx bower install

script:
  - xvfb-run npx -c "wct"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      npx -c "wct --plugin sauce";
    fi

before_deploy: gulp
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/public
  github-token: $GITHUB_TOKEN
  on:
    branch: master
