---
git:
  depth: 5
sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - app/bower_components
    - node_modules

language: node_js
node_js: node

before_script: npx bower install

before_deploy: gulp
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/public
  github-token: $GITHUB_TOKEN
  on:
    branch: master
