---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache:
  yarn: true
  directories:
    - $TRAVIS_BUILD_DIR/packages/pwa/app/bower_components

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - cd
  - yarn config set workspaces-experimental true
  - cd -
  - rm -rf node_modules packages/*/node_modules
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then
      export SAUCE_ACCESS_KEY=$PR_SAUCE_ACCESS_KEY;
      export SAUCE_USERNAME=$PR_SAUCE_USERNAME;
    fi

script:
  - cd packages/pwa
  - xvfb-run yarn run wct
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      yarn run wct -- --plugin sauce;
    fi
  - cd ../..

before_deploy:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/packages/pwa/dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
